version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
    # volumes:
    #   - /var/lib/postgresql/data:/var/lib/postgresql/data
  nqueens:
    image: nqueens:latest
    command: python main.py
    environment:
      - BOARD_SIZE=9
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_NAME=postgres
    depends_on:
      - db